In [2]:
import pandas as pd
import numpy as np
import nbformat 

prescriptions = pd.read_csv("/Users/are/Development/DA229/PythonHackathon/Python_Hackathon_Sep_2026/cardiac_failure/patient_precriptions.csv")

print(prescriptions.shape)       # 2,008 rows, 107 columns
display(prescriptions.head())
prescriptions.info()

(15362, 2)

   inpatient_number                                         drug_name
0            857781                  sulfotanshinone sodium injection
1            857781                                 Furosemide tablet
2            857781                       Enoxaparin Sodium injection
3            857781  Meglumine Adenosine Cyclophosphate for injection
4            857781                              Furosemide injection

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15362 entries, 0 to 15361
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   inpatient_number  15362 non-null  int64
 1   drug_name         15362 non-null  object
dtypes: int64(1), object(1)
memory usage: 240.2+ KB

In [3]:
prescriptions.dtypes

inpatient_number     int64
drug_name           object
dtype: object

In [4]:
prescriptions.isna()

       inpatient_number  drug_name
0                 False      False
1                 False      False
2                 False      False
3                 False      False
4                 False      False
...                 ...        ...
15357             False      False
15358             False      False
15359             False      False
15360             False      False
15361             False      False

[15362 rows x 2 columns]

In [5]:
prescriptions.isna().sum()

inpatient_number    0
drug_name           0
dtype: int64

In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("/Users/are/Development/DA229/PythonHackathon/Python_Hackathon_Sep_2026/cardiac_failure/patient_precriptions.csv")

# 1) Basic inspection
print(df.shape)
print(df.head())
print(df.isna().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate patient-drug pairs:", df.duplicated(subset=["inpatient_number", "drug_name"]).sum())

(15362, 2)
   inpatient_number                                         drug_name
0            857781                  sulfotanshinone sodium injection
1            857781                                 Furosemide tablet
2            857781                       Enoxaparin Sodium injection
3            857781  Meglumine Adenosine Cyclophosphate for injection
4            857781                              Furosemide injection
inpatient_number    0
drug_name           0
dtype: int64
Duplicate rows: 0
Duplicate patient-drug pairs: 0

In [7]:
# 2) Clean patient ID
df = df.rename(columns={'inpatient_number': 'patient_id'})

In [ ]:
# 3) Clean drug names
# Keep as string so text cleaning and grouping does not coerce it to numeric
# or create unexpected dtype changes.
df["drug_name"] = df["drug_name"].astype("string")

df["drug_name"] = df["drug_name"].str.strip()df["drug_name"] = df["drug_name"].str.lower()
df["drug_name"] = df["drug_name"].str.replace(r"\s+", " ", regex=True)

In [10]:
# 4) Remove blank or missing drug entries
df = df[df["drug_name"].notna() & df["drug_name"].str.strip().ne("")]

In [ ]:
df.shape
df.dtypes
print(df["drug_name"].dtype)

patient_id     int64
drug_name     object
dtype: object